# Generated by Django 5.0.1 on 2024-02-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='current_answer',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='questao',
            name='times_solved',
            field=models.IntegerField(default=0),
        ),
    ]
