# Generated by Django 5.0.1 on 2024-02-12 00:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_alter_questao_current_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='current_answer',
            field=ckeditor.fields.RichTextField(blank=True, default=None),
        ),
    ]
