# Generated by Django 5.0.1 on 2024-05-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_remove_questao_current_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solucao',
            old_name='body',
            new_name='bodysol',
        ),
    ]
