# Generated by Django 5.0.1 on 2024-01-24 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Apenas letras são permitidas no campo Name.', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
