# Generated by Django 5.0.1 on 2024-01-31 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espaco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espaco.espaco'),
        ),
        migrations.AddField(
            model_name='questao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espaco.questao'),
        ),
        migrations.AddField(
            model_name='tag',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espaco.espaco'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='tags',
            field=models.ManyToManyField(to='espaco.tag'),
        ),
    ]
