# Generated by Django 5.0.1 on 2024-02-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='space',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
