# Generated by Django 5.0.1 on 2024-01-24 20:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0004_remove_espaco_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
