# Generated by Django 5.0.1 on 2024-07-17 21:01

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0004_alter_tag_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
