# Generated by Django 5.0.1 on 2024-01-24 20:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0005_espaco_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaco',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
