# Generated by Django 5.0.1 on 2024-01-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0006_alter_espaco_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaco',
            name='title',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
