# Generated by Django 5.0.1 on 2024-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0008_questao_alternativa_tag_questao_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaco',
            name='description',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
