# Generated by Django 5.0.1 on 2024-08-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0008_alter_espaco_user_alter_tag_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name_normalized']},
        ),
        migrations.AddField(
            model_name='tag',
            name='name_normalized',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
