# Generated by Django 5.0.1 on 2024-08-17 02:47

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0009_alter_tag_options_tag_name_normalized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.text.Lower(django.db.models.functions.comparison.Cast('street_number', output_field=models.IntegerField()))]},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_normalized',
        ),
    ]
