# Generated by Django 5.0.1 on 2024-08-17 02:56

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0010_alter_tag_options_remove_tag_name_normalized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
