# Generated by Django 5.0.1 on 2024-08-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0011_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
