# Generated by Django 5.0.1 on 2024-08-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaco', '0012_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
